indeed_symfony/indeed/src/Entity/Offres.php
<?php

namespace App\Entity;

use App\Repository\OffresRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OffresRepository::class)
 */
class Offres
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Ville;

    /**
     * @ORM\Column(type="date")
     */
    private $Date_creation;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_maj;

    /**
     * @ORM\ManyToOne(targetEntity=Contrats::class, inversedBy="offres")
     * @ORM\JoinColumn(nullable=false)
     */
    private $key_contrats;

    /**
     * @ORM\ManyToOne(targetEntity=TypeContrats::class, inversedBy="offres")
     * @ORM\JoinColumn(nullable=false)
     */
    private $key_type_contrats;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $fin_mission;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->Date_creation;
    }

    public function setDateCreation(\DateTimeInterface $Date_creation): self
    {
        $this->Date_creation = $Date_creation;

        return $this;
    }

    public function getDateMaj(): ?\DateTimeInterface
    {
        return $this->date_maj;
    }

    public function setDateMaj(\DateTimeInterface $date_maj): self
    {
        $this->date_maj = $date_maj;

        return $this;
    }

    public function getKeyContrats(): ?Contrats
    {
        return $this->key_contrats;
    }

    public function setKeyContrats(?Contrats $key_contrats): self
    {
        $this->key_contrats = $key_contrats;

        return $this;
    }

    public function getKeyTypeContrats(): ?TypeContrats
    {
        return $this->key_type_contrats;
    }

    public function setKeyTypeContrats(?TypeContrats $key_type_contrats): self
    {
        $this->key_type_contrats = $key_type_contrats;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getFinMission(): ?\DateTimeInterface
    {
        return $this->fin_mission;
    }

    public function setFinMission(?\DateTimeInterface $fin_mission): self
    {
        $this->fin_mission = $fin_mission;

        return $this;
    }
}

indeed_symfony/indeed/src/Controller/IndeedController.php
<?php

namespace App\Controller;

use App\Entity\Offres;
use App\Repository\ContratsRepository;
use App\Repository\OffresRepository;
use App\Repository\TypeContratsRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\DependencyInjection\Security\UserProvider\EntityFactory;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class IndeedController extends AbstractController
{
    /**
     * @Route("/", name="offre")
     */
    public function index(OffresRepository $repository): Response
    {
        $offres = $repository->findAll();

        return $this->render('indeed/index.html.twig', [
            'offres' => $offres
        ]);
    }

    /**
     * @Route("/form",name="offre.form")
     */
    public function form(Request $request, EntityManagerInterface $manager_interface, ContratsRepository $contrat, TypeContratsRepository $type_contrat): Response
    {
        $offre = new Offres;
        $cdd = $contrat->findOneBy(["titre" => "CDD"]);
        $cdi = $contrat->findOneBy(["titre" => "CDI"]);
        $freelance = $contrat->findOneBy(["titre" => "Freelance"]);
        $tempsPlein = $type_contrat->findOneBy(["titre" => "Temps Plein"]);
        $tempsPartiel = $type_contrat->findOneBy(["titre" => "Temps Partiel"]);
        $form = $this->createFormBuilder($offre)
            ->add("Title", TextType::class)
            ->add("Description", TextType::class)
            ->add("Adresse", TextType::class)
            ->add("Code_postal", TextType::class)
            ->add("Ville", TextType::class)
            ->add("Fin_mission", DateType::class)
            ->add("key_contrats", ChoiceType::class, [
                'choices' => [
                    'CDI' => $cdd,
                    'CDD' => $cdi,
                    'Freelance' => $freelance,
                ],
            ])

            ->add("key_type_contrats", ChoiceType::class, [
                'choices' => [
                    'Temps plein' => $tempsPlein,
                    'Temps partiel' => $tempsPartiel,
                ],
            ], ['label' => "Choix du type de contrat"],)
            ->add("Envoyer", SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-primary',
                    'role' => 'button',
                ]
            ])
            ->getForm();
        if (empty($offre->getDateCreation())) {
            $offre->setDateCreation(new \DateTime('now'));
        } else {
            $offre->setDateMaj(new \DateTime('now'));
        }
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $manager_interface->persist($offre);
            $manager_interface->flush();
        }
        if ($form->isSubmitted() && $form->isValid()) {
            return $this->redirect('/');
        }
        return $this->render('indeed/form.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/offres/{id}",name="offre.show")
     */
    public function show(Offres $offre)
    {
        return $this->render('indeed/offre.html.twig', [
            'offre' => $offre
        ]);
    }

    /**
     * @Route("/gestion", name="offre.gestion")
     */
    public function gestion(OffresRepository $repository): Response
    {
        $offres = $repository->findAll();

        return $this->render('indeed/gestion.html.twig', [
            'offres' => $offres
        ]);
    }

    /**
     * @Route("/gestion/{id}",name="offre.crud")
     */
    public function crud(Offres $offre, Request $request, EntityManagerInterface $manager_interface, ContratsRepository $contrat, TypeContratsRepository $type_contrat)
    {
        $cdd = $contrat->findOneBy(["titre" => "CDD"]);
        $cdi = $contrat->findOneBy(["titre" => "CDI"]);
        $freelance = $contrat->findOneBy(["titre" => "Freelance"]);
        $tempsPlein = $type_contrat->findOneBy(["titre" => "Temps Plein"]);
        $tempsPartiel = $type_contrat->findOneBy(["titre" => "Temps Partiel"]);
        $form = $this->createFormBuilder($offre)
            ->add("Title", TextType::class)
            ->add("Description", TextType::class)
            ->add("Adresse", TextType::class)
            ->add("Code_postal", TextType::class)
            ->add("Ville", TextType::class)
            ->add("Fin_mission", DateType::class)
            ->add("key_contrats", ChoiceType::class, [
                'choices' => [
                    'CDI' => $cdd,
                    'CDD' => $cdi,
                    'Freelance' => $freelance,
                ],
            ])

            ->add("key_type_contrats", ChoiceType::class, [
                'choices' => [
                    'Temps plein' => $tempsPlein,
                    'Temps partiel' => $tempsPartiel,
                ],
            ], ['label' => "Choix du type de contrat"],)
            ->add("Envoyer", SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-primary',
                    'role' => 'button',
                ]
            ])
            ->getForm();
        if (empty($offre->getDateCreation())) {
            $offre->setDateCreation(new \DateTime('now'));
        } else {
            $offre->setDateMaj(new \DateTime('now'));
        }
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $manager_interface->persist($offre);
            $manager_interface->flush();
        }
        if ($form->isSubmitted() && $form->isValid()) {
            return $this->redirect('/');
        }
        return $this->render('indeed/crud.html.twig', [
            'form' => $form->createView(),
            'offre' => $offre
        ]);
    }


    /**
     * @Route("/delete/{id}", name="offre.delete")
     */
    public function delete(Offres $offre, EntityManagerInterface $manager_interface): Response
    {
        $manager_interface->remove($offre);
        $manager_interface->flush();
        return $this->redirect('/gestion');
    }
}

indeed_symfony/indeed/templates/indeed/crud.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formulaire
{% endblock %}

{% block body %}
	<div class="container">
		<h1 class="row justify-content-center">
			Modification de l'annonce "{{ offre.title }}" :
		</h1>
		{{ form_start(form) }}
		<div id="erreur">
			{{ form_errors(form) }}
		</div>
		<div id="titre" class="card">
			<h4>Titre :</h4>
			{{ form_widget(form.Title) }}
			<h4>Description :</h4>
			{{ form_widget(form.Description) }}
			<h4>Choix du contrat :</h4>
			{{ form_widget(form.key_contrats) }}
			<h4>Date de fin de mission :</h4>
			{{ form_widget(form.Fin_mission) }}
			<h4>Adresse :</h4>
			{{ form_widget(form.Adresse) }}
			<h4>Code postal :</h4>
			{{ form_widget(form.Code_postal) }}
			<h4>Ville :</h4>
			{{ form_widget(form.Ville) }}
			<h4>Choix du type de contrat :</h4>
			{{ form_widget(form.key_type_contrats) }}
			<div class="row justify-content-center marge">
				{{ form_end(form) }}
			</div>
		</div>

	</div>
{% endblock %}

indeed_symfony/indeed/templates/indeed/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formulaire
{% endblock %}

{% block body %}
	<div class="container">
		<h1 class="row justify-content-center">
			Ajout d'une annonce :
		</h1>
		{{ form_start(form) }}
		<div id="erreur">
			{{ form_errors(form) }}
		</div>
		<div id="titre" class="card">
			<h4>Titre :</h4>
			{{ form_widget(form.Title) }}
			<h4>Description :</h4>
			{{ form_widget(form.Description) }}
			<h4>Choix du contrat :</h4>
			{{ form_widget(form.key_contrats) }}
			<h4>Date de fin de mission :</h4>
			{{ form_widget(form.Fin_mission) }}
			<h4>Adresse :</h4>
			{{ form_widget(form.Adresse) }}
			<h4>Code postal :</h4>
			{{ form_widget(form.Code_postal) }}
			<h4>Ville :</h4>
			{{ form_widget(form.Ville) }}
			<h4>Choix du type de contrat :</h4>
			{{ form_widget(form.key_type_contrats) }}
			<div class="row justify-content-center marge">
				{{ form_end(form) }}
			</div>
		</div>

	</div>
{% endblock %}

indeed_symfony/indeed/templates/indeed/gestion.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des annonces
{% endblock %}

{% block body %}

	<div class="container">
		<h1 class="row justify-content-center" style="margin-bottom:2%">
			Gestion des annonces :
		</h1>
		<div class="row justify-content-center">
			<a href="/" role="button" class="btn btn-primary">Accueil</a>
		</div>
		<div class="row">
			{% for offre in offres %}
				<div class="col-md-3 marge">
					<div class="card">
						<div class="card-body">
							<h5 class="card-title center">{{offre.title}}</h5>
							<p class="card-text center">{{offre.ville}}</p>
							<p class="card-text center">{{offre.keycontrats.titre}}</p>
							<p class="card-text center">{{offre.keytypecontrats.titre}}</p>
							<div class="row justify-content-center">
								<a href="/gestion/{{offre.id}}" role="button" class="btn btn-primary marge">Modifier offre</a>
								<a href="/delete/{{offre.id}}" role="button" class="btn btn-primary marge">Supprimer offre</a>
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

indeed_symfony/indeed/templates/indeed/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste offres
{% endblock %}

{% block body %}

	<div class="container">
		<h1 class="row justify-content-center" style="margin-bottom:2%">
			Liste des offres disponibles :
		</h1>
		<div class="row justify-content-around creation decaler_bouton">
			{% if app.user %}
				<a href="/form" role="button" class="btn btn-primary">Ajouter une annonce</a>
				<a href="{{ path('app_logout') }}" role="button" class="btn btn-primary">Déconnexion</a>
				<a href="/gestion" role="button" class="btn btn-primary">Gestion</a>

			{% else %}
				<a href="/register" role="button" class="btn btn-primary">S'inscrire</a>
				<a href="/login" role="button" class="btn btn-primary">Se connecter</a>
			{% endif %}
		</div>
		<div class="row">
			{% for offre in offres %}
				<div class="col-md-3 marge">
					<div class="card">
						<div class="card-body">
							<h5 class="card-title center">{{offre.title}}</h5>
							<p class="card-text center">{{offre.ville}}</p>
							<p class="card-text center">{{offre.keycontrats.titre}}</p>
							<p class="card-text center">{{offre.keytypecontrats.titre}}</p>
							<div class="row justify-content-center">
								<a href="/offres/{{offre.id}}" role="button" class="btn btn-primary">voir offre</a>
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

indeed_symfony/indeed/templates/indeed/offre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offre
	{{ offre.title}}
{% endblock %}

{% block body %}
	<div class="container">
		<h1 class="row justify-content-center">
			Offre :
			{{ offre.title }}
		</h1>
		<div class="card" style="margin-top: 10%">
			<p>
				Description :
				{{ offre.Description }}
			</p>
			<p>
				Adresse :
				{{ offre.Adresse}}
			</p>
			<p>
				Code postal :
				{{ offre.codepostal}}
			</p>
			<p>
				Ville :
				{{ offre.Ville}}
			</p>
			<p>
				Date de création :
				{{offre.datecreation  | date("d/m/Y")}}
			</p>
			<p>
				Date de mise à jour :
				{{offre.datemaj  | date("d/m/Y")}}
			</p>
			{% if offre.keycontrats.titre == 'CDI' %}
				{% else %}
					<p>
						Date de fin de mission :
						{{offre.finmission  | date("d/m/Y")}}
					</p>
			{% endif %}
			<p>
				Contrat :
				{{ offre.keycontrats.titre}}
			</p>
			<p>
				Type de contrat :
				{{ offre.keytypecontrats.titre}}
			</p>

			<button type="button" class="btn btn-primary">Postuler</button>
		</div>

		<a href="/" role="button" class="btn btn-secondary">retour</a>
	</div>
{% endblock %}